# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Check Home Assistant Configuration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    - name: Install dependencies
      run: |
        cp secrets_dummy.yaml secrets.yaml
        touch home-assistant_v2.db
        touch home-assistant.log
        pip3 install homeassistant
    - name: Validate configuration
      run: |
        - hass --script check_config -c . -f